### ISSUE TITLE
Error when using ; as delimiter in s command

### ISSUE THREAD

**Issue by aureliojargas** [aureliojargas/sedsed#12]
``` console
$ sedsed -e 's;foo;bar;'
Traceback (most recent call last):
  File "/usr/bin/sedsed", line 1346, in <module>
    cmd = SedCommand(possiblecmd)
  File "/usr/bin/sedsed", line 633, in __init__
    self.do_it_all()
  File "/usr/bin/sedsed", line 690, in do_it_all
    self.delimiter = self.junk[0]
IndexError: string index out of range
$
```

When fixed, remove the exception in `test/gnused/run`.

**Comment by aureliojargas** [comment]
Fixed by the new `sedparse` parser, see #52.

```console
$ ./sedsed.py -e 's;foo;bar;'
s;foo;bar;
$
```
